.gitmodules
client.go

Intentionally modeled on consul APIs
(https://godoc.org/github.com/hashicorp/consul/api)
R: @xichen2020 @robskillington

Add cluster interfaces

---

placement/placement.go
placement/placement_test.go

Marshal placement snapshot as maps instead of arrays

---

placement/algo/algo.go
placement/algo/algo_test.go
placement/algo/helper.go
placement/interface.go
placement/placement.go
placement/placement_test.go
placement/service/placementservice.go
placement/service/placementservice_test.go

add placement option to loose rack check during host replacement

---

client.go

R: @xichen2020 @robskillington @cw9

Add version and CAS to KVStore interface

---

.ci/build-common.sh
.travis.yml
Makefile
glide.lock
glide.yaml

R: @robskillington @xichen2020

Convert to glide

---

glide.lock
glide.yaml

Lock glide version

---

client.go
shard.go

@xichen2020 @robskillington @martin-mao @mmihic

Add WatchInstances to Service interface

---

services/mock_services.go
services/services.go

Add missing setters to Service, ServiceReplication and ServiceSharding

---

services/mock_services.go
services/services.go

Rename ServiceSharding Len method to NumShards

---

services/services.go
shard/shard.go

add Instance() and ShardIDs()

---

services/mock_services.go
services/services.go

Implement Instance()

---

changeset/manager.go
changeset/manager_test.go

Getter pattern change

---

kv/fake_store.go
kv/store.go

cc @robskillington @martin-mao @xichen2020

Add ValueWatchable

---

kv/fake_store_test.go
kv/store.go

cc @xichen2020 @robskillington @martin-mao

Handle nil Value

---

.excludelint
.travis.yml
placement/algo/algo.go
placement/placement.go
placement/planner/planner.go
placement/planner/planner_test.go

Modify the deployment planner to do bigger batch first

---

placement/algo/algo.go
placement/algo/algo_test.go
placement/algo/helper.go
placement/placement.go
placement/placement_test.go
placement/planner/planner_test.go
placement/service/placementservice.go
placement/service/placementservice_test.go
placement/types.go

cc @xichen2020 @robskillington

Consider weights in placement algorithm

---

placement/service/placementservice.go
placement/service/placementservice_test.go
placement/types.go

Return placement from placement service

---

placement/placement.go
placement/placement_test.go
placement/service/placementservice.go
placement/service/placementservice_test.go

Make the replace function deterministic given the same set of hosts

Sort hosts by id before knapsack

---

placement/options.go
placement/placement.go
placement/placement_test.go
placement/service/placementservice.go
placement/service/placementservice_test.go
placement/types.go

@xichen2020 
Modify the json marshalling for placement snapshot, I'll remove the multi-cluster placement in statsdex. Will wait until the statsdex change is done to merge this in.

Modify Placement json marshalling

---

placement/algo/algo.go
placement/algo/algo_test.go
placement/algo/helper.go
placement/placement.go
placement/placement_test.go
placement/planner/planner_test.go
placement/service/placementservice_test.go

renamed NewHostShards to NewEmptyHostShards
renamed newHostShards to NewHostShards

Expose constructor for HostShards

---

services/services.go
services/types.go

move interfaces to types.go
@robskillington

Separate service interface and implementation

---

services/placement/planner/planner.go
services/placement/planner/planner_test.go

Produce deterministic steps in deployment planner

---

services/placement/algo/algo.go
services/placement/algo/algo_test.go
services/placement/algo/helper_test.go
services/placement/placement.go
services/placement/placement_test.go
services/placement/planner/planner_test.go
services/placement/service/placementservice_test.go

Fill in Endpoint field when adding instance

---

kv/etcd/etcd.go
kv/etcd/etcd_test.go
kv/etcd/options.go
kv/store.go

Use etcd revision instead of key version to compare values

Add cache to kv client

---

services/client/options.go
services/client/services_test.go

Return correct error

---

services/services.go
services/types.go

Add a String() to Metadata interface

---

services/client/services_test.go
services/client/storage_test.go
services/client/util.go
services/placement/algo/algo_test.go
services/placement/algo/helper.go
services/placement/algo/helper_test.go
services/placement/placement.go
services/placement/placement_test.go
services/placement/planner/planner_test.go
services/placement/service/placementservice_test.go
services/types.go

to make adding fields easier in the future

Add setters to ServicePlacement interface

---

services/placement/algo/algo_test.go
services/placement/algo/helper.go
services/placement/algo/helper_test.go

Fix a sharding corner case

---

services/placement/options.go
services/placement/placement_test.go
services/placement/service/placementservice.go
services/placement/service/placementservice_test.go
services/types.go

@xichen2020 @robskillington @martin-mao

Add Dryrun to placement options

---

services/placement/service/placementservice.go
services/placement/service/placementservice_test.go
services/types.go

@xichen2020 @robskillington @martin-mao

Add SetPlacement() to PlacementService and return version in Placement()

---

client/etcd/client.go
client/etcd/client_test.go
client/etcd/options.go
client/etcd/options_test.go
kv/etcd/store.go

Add etcd based config service client

---

client/etcd/client.go
client/etcd/client_test.go
client/etcd/options.go
client/etcd/options_test.go
kv/etcd/store.go

Add validation to config service options, add tag to metric scope

---

services/client/services.go
services/heartbeat/etcd/store.go
services/heartbeat/etcd/store_test.go
services/heartbeat/types.go

Reuse lease in heartbeat store

---

services/placement/options.go
services/placement/placement_test.go
services/placement/service/placementservice.go
services/types.go

Add log for dryrun

---

.travis.yml

@xichen2020 @robskillington @prateek

Pin glide to v0.12.3

---

client/etcd/client.go
client/etcd/client_test.go
kv/etcd/store.go
kv/etcd/store_test.go
services/client/options.go
services/client/services.go
services/client/services_test.go
services/client/storage.go
services/client/storage_test.go
services/heartbeat/etcd/options.go
services/heartbeat/etcd/store.go
services/heartbeat/etcd/store_test.go
services/heartbeat/types.go

Add Watch to heartbeat store and use in service discovery client

---

services/client/services.go

Fix typo in metric name

---

.travis.yml

/cc @cw9 @robskillington @xichen2020

Drop Go1.6 Travis builds

---

services/heartbeat/etcd/store_test.go

@prateek @xichen2020 @robskillington

Fix flaky test

---

.travis.yml
Makefile

- fix all-gen target
- reuse common.mk glide install target
- fix proto-gen header addition
/cc @cw9 @xichen2020

Fix makefile codegen, reuse .ci/common.mk

---

kv/etcd/store_test.go
services/placement/algo/sharded_helper.go
services/placement/algo/sharded_helper_test.go

Addressing: https://github.com/m3db/m3cluster/issues/81

Prefer to return the Initializing shards back to source instance

---

client/mock_client.go
kv/etcd/store.go
kv/etcd/store_test.go
kv/mem/store.go
kv/mem/store_test.go
kv/mock_store.go
kv/types.go
services/mock_services.go

Add a History function to get values of past versions

Add History function to kv API

---

services/client/services.go
services/client/services_test.go

When we start advertising it takes as long as the heartbeat interval
duration to begin advertising. Ideally a service shouldn't start
advertising until it's ready, so when it starts it might make sense to
show the advertisement immediately. Even if it's not ready at first, if
it has a health function it won't start heartbeating until it's ready
anyway.
RFR @cw9

[advertisement] Tick immediately on start

---

kv/mem/store.go
kv/mem/store_test.go

To be used in tests
@xichen2020 @schallert

Update watch when Delete is called in mem.Store

---

etcd/watchmanager/manager.go

Cancel context in etcd.Watch() call when there is a timeout

---

kv/etcd/store.go
kv/etcd/store_test.go
kv/op.go
kv/types.go

Add implementation of TxnStore

---

client/client.go
client/etcd/client.go
client/etcd/client_test.go
kv/etcd/store.go
kv/etcd/store_test.go
kv/mem/store.go
kv/mem/store_test.go
kv/types.go

Expose TxnStore from m3cluster client

---

glide.lock
glide.yaml

Up m3x version

---

kv/util/util.go
kv/util/util_test.go

@xichen2020 @prateek @robskillington

Allow closing the watch util functions

---

client/etcd/client.go
client/etcd/client_test.go
client/etcd/config.go
client/etcd/config_test.go
client/etcd/options.go
client/etcd/options_test.go
etcd/watchmanager/manager_test.go
glide.lock
glide.yaml
services/client/options.go
services/client/services.go

@xichen2020 @robskillington @prateek

Migrate config for etcd based config service client

---

.travis.yml
Makefile
client/mock_client.go
kv/mock_store.go
services/mock_services.go
services/placement/service/placementservice.go
services/placement/service/placementservice_test.go
services/types.go

- update travis configs to meet expectations from ci-scripts
- expose instance used information from PlacementService 
/cc  @cw9 @xichen2020

Update Placement Service Interface

---

client/etcd/client.go
client/etcd/client_test.go

Add leading slash to keys, fix store creation with namespaces

---

kv/etcd/store_test.go

I've run into this race a few times on builds for other PRs (example:
https://travis-ci.org/m3db/m3cluster/builds/240110273#L1113)  and think
this should fix it (specifically the race between `require.NoError()`
and the testing object `t` itself, not necessarily the grpc error).
EDIT: Actually I think this should may the grpc error as well since all of
the `store.Set` calls should be fully finished before we start closing the
etcd server.

[test] Kv/etcd: prevent TestWatchLastVersion race

---

services/placement/config.go
services/placement/config_test.go

Change WatcherConfiguration.NewOptions interface

---

services/leader/election/client.go
services/leader/election/client_test.go
services/leader/election/options.go

Pulling this in now since it was stamped in m3x and will reduce the size
of the final leader PR.

[services] Leader: election helper package

---

glide.lock
glide.yaml
integration/etcd/etcd.go
integration/etcd/etcd_test.go
integration/etcd/options.go
integration/etcd/types.go

/cc @robskillington @xichen2020 @cw9

Add embedded etcd server for integration tests

---

client/client_mock.go
services/services_mock.go

cc @jeromefroe @cw9 
This PR regenerates the mock client and services due to recent interface change.

Regenerate mock client and services

---

placement/algo/mirrored.go
placement/algo/mirrored_test.go
placement/algo/sharded.go
placement/algo/sharded_helper.go
placement/algo/sharded_test.go
placement/placement.go
placement/placement_test.go
placement/selector/common.go
placement/selector/mirrored.go
placement/types.go

Supports backing out of add/remove/replace for mirror mode.

Support reverting previous change for mirror mode

---

placement/algo/mirrored.go
placement/algo/mirrored_test.go
placement/algo/non_sharded.go
placement/algo/sharded.go
placement/algo/sharded_helper.go
placement/placement.go
placement/placement_test.go
placement/types.go
shard/shard.go
shard/shard_test.go
shard/types.go

move the Clone() functions out from placement.go
@xichen2020

Add Clone to Shard, Instance and Placement interface

---

placement/placement.go
placement/staged_placement.go
placement/staged_placement_test.go

So I can access this function in statsdex
@xichen2020

Expose ActiveIndex on Placements

---

changeset/manager.go
client/etcd/client.go
client/etcd/config_test.go
etcd/watchmanager/manager.go
glide.lock
glide.yaml
integration/etcd/etcd.go
kv/etcd/options.go
kv/etcd/store.go
kv/util/runtime/value.go
kv/util/types.go
kv/util/util.go
placement/algo/sharded_helper.go
placement/selector/mirrored.go
placement/service/service.go
placement/storage/storage.go
services/client/etcd/services.go
services/client/etcd/services_test.go
services/heartbeat/etcd/options.go
services/heartbeat/etcd/store.go

This PR pulls in the latest version of m3x and updates package imports accordingly.

[glide] Update m3x dependency and fix package imports accordingly

---

placement/placement_mock.go
placement/service/service.go
placement/service/service_test.go
placement/storage/storage.go
placement/storage/storage_test.go
placement/types.go

Add CheckAndSet to Storage interface

---

kv/util/runtime/value.go
kv/util/runtime/value_test.go

cc @cw9 @jeromefroe 
This PR handles runtime value deletions and stale updates gracefully. It ignores the deletion event and returns an error, but processes new updates just like others. Stale updates are also ignored.

Handle deletions and stale updates gracefully

---

client/client.go
client/client_mock.go
client/etcd/client.go
client/etcd/client_test.go
kv/store.go
kv/store_mock.go
kv/types.go
placement/placement_mock.go

Create KV store with custom zone and env

---

kv/etcd/store.go

Add logging to kv updates

---

client/etcd/client.go
client/etcd/client_test.go
kv/config.go
kv/store.go
kv/store_mock.go
kv/types.go

Add configuration for kv options

---

kv/util/lock.go
kv/util/lock_test.go
kv/util/util.go

Add a watch utility for *[]string
@xichen2020 @jeromefroe

Add WatchAndUpdateStringArrayPointer

---

placement/storage/helper.go
placement/storage/helper_test.go
placement/storage/storage_test.go
services/heartbeat/etcd/store_test.go

Ensure new placement is scheduled later than existing placements

---

client/etcd/client.go
client/etcd/client_test.go
integration/etcd/etcd.go
integration/etcd/options.go
integration/etcd/types.go
kv/config.go

Use default value when no override is provided in kv options

---

client/etcd/client.go
client/etcd/client_test.go
kv/config.go
kv/store.go
kv/store_mock.go
kv/types.go

cc @cw9 @jeromefroe 
This PR makes the logger of a KV store configurable.

Make the logger of a KV store configurable

---

client/etcd/client.go
client/etcd/client_test.go
integration/etcd/etcd.go
integration/etcd/etcd_test.go
integration/etcd/options.go
integration/etcd/types.go
kv/config.go
kv/config_test.go
kv/store.go
kv/store_test.go
kv/types.go

Add zone to kv options

---

kv/store_mock.go
placement/placement_mock.go
placement/service/service_test.go
placement/storage/helper.go
placement/storage/helper_test.go
placement/storage/storage.go
placement/storage/storage_test.go
placement/types.go

So we can read placement in the history
@prateek @xichen2020

Expose history function in placement storage interface

---

placement/algo/mirrored.go
placement/algo/sharded.go
placement/algo/sharded_helper.go
placement/algo/sharded_helper_test.go
placement/algo/sharded_test.go
placement/storage/helper.go
placement/storage/storage.go

Hide some functions/interfaces that are not used outside the package and can change internal state
@xichen2020

Update some internal interfaces

---

.travis.yml
glide.lock
glide.yaml

Pull latest m3x

---

glide.lock
glide.yaml
kv/util/runtime/value.go
kv/util/runtime/value_test.go

Depends on https://github.com/m3db/m3x/pull/138

Use watch.Value in runtime.Value

---

services/config.go
services/config_test.go

This seemed to be a general config that should live in the repo.

Add ElectionConfiguration struct to services config
