m3db/m3cluster

services/placement/placement.go
services/placement/placement_test.go
services/placement/service/placementservice.go
services/placement/service/placementservice_test.go
services/services.go
services/types.go
shard/shard.go

cc @cw9 @xichen2020 @martin-mao @ben-lerner @prateek 
Outstanding question for @cw9 : when do the leaving shards get removed and then also when is instance completely taken out of the placement?  What calls to the `PlacementService` achieve this?

Rely on external callers marking shards available

---

services/placement/algo/helper.go
services/placement/algo/helper_test.go
services/placement/placement.go
services/placement/placement_test.go

Fix an edge case caused by:
1, add a node, so it will be assigned with some shards in Initializing state, with sourceID to reference where these shards come from.
2, remove this node before it finish bootstrapping it's shards
3, the Initializing shard will be moved to another node but the sourceID got lost.
@robskillington

Carry sourceID when moving an Initializing shard

---

client/client.go
client/mock_client.go
services/mock_services.go

Some config service client user only needs a KV client or a Services
client, not both. This interface change allows us to create those
clients lazily.

Modify ConfigServiceClient interface

---

glide.lock
glide.yaml

Pinning to a verified SHA in https://github.com/coreos/etcd/commits/release-3.1 since our etcd servers are upgraded to the 3.1 release
cc @xichen2020 @robskillington @pjjw

Pin etcd to version release-3.1

---

services/placement/algo/sharded.go
services/placement/algo/sharded_test.go
services/placement/service/placementservice.go
services/placement/service/placementservice_test.go

Previously when adding an instance, we bail if the adding instance is already in placement,
this diff adds an exception if the existing instance is a leaving instance, meaning it has only Leaving shards.
This supports backing out of an instance removal operation.
The algo will first try taking those leaving shards back, and then do a normal addInstance if necessary to even the load.
@robskillington @xichen2020

Allow adding leaving instance back to placement

---

services/client/storage.go
services/client/storage_test.go
services/mock_services.go
services/placement/placement.go
services/placement/placement_test.go
services/types.go

In some placement-related methods we return the version of the key/value
pair in etcd along with the `ServicePlacement` (for example from
`PlacementService.Placement()`). There are cases where it's useful to
have the version follow that `ServicePlacement` object, so this expands
that interface to provide access to the version.
RFR @cw9

[placement] Add GetVersion() + SetVersion() funcs

---

services/client/services.go
services/client/services_test.go
services/heartbeat/etcd/store.go
services/heartbeat/etcd/store_test.go
services/heartbeat/types.go

Previously the Unadvertise call will only stop the go routine that keeps heartbeating the instance, now it also deletes the heartbeat in the data store.
@xichen2020 @robskillington @prateek

Change Unadvertise to clean up the existing heartbeat for the instance

---

client/etcd/client.go
client/etcd/client_test.go
kv/etcd/options.go
kv/etcd/store.go
kv/etcd/store_test.go
services/client/services_test.go

Remove the KeyFn() in the kv options and add ApplyPrefix() to prevent
users from adding suffix to the key, which might cause issues in etcd
usage in the future
For example: etcd allows adding a WithPrefix() in the Get calls, but if
the key we passed in was wrapped with a suffix, the result might be
confusing.
@xichen2020 @robskillington @schallert @prateek

Change KeyFn() to ApplyPrefix() in etcd kv options

---

services/placement/algo/sharded.go
services/placement/algo/sharded_helper.go
services/placement/algo/sharded_helper_test.go
services/placement/algo/sharded_test.go

Previously when backing out from a replace, the empty instance in the
placement is not being cleaned up, this diff fixes that.

Fix bug in backing out of a replace

---

client/etcd/client.go
kv/etcd/store.go
kv/etcd/store_test.go
kv/mem/store.go
kv/mem/store_test.go
kv/types.go
services/client/services.go
services/client/services_test.go

So that the config for service discovery watch timeout will always try a Get() and is independent
from the config for watch creation timeout and/or get request timeouts

Call Get() after service discovery watch timed-out for initial value

---

services/placement/options.go
services/placement/service/placementservice.go
services/placement/service/placementservice_test.go
services/types.go

When adding instances to a placement we check that the candidates have
the same zone as those in the placement. When a placement is empty we
need to explicitly set the zone to be considered valid.

[placement] Options: add ValidZone + SetValidZone

---

services/client/storage.go
services/placement/service/placementservice.go
services/placement/service/placementservice_test.go
services/placement/types.go

cc @cw9 @robskillington 
This PR adds `Set` to the storage interface so we can write out new placements without reading from the store first.

Add Set() to the Storage interface

---

kv/types.go
kv/util/runtime/options.go
kv/util/runtime/value.go
kv/util/runtime/value_test.go

cc @cw9 @jeromefroe @martin-mao 
This PR adds the runtime value interface to m3cluster, which provides the ability to watch / unwatch updates and process the updates using the configurable unmarshalling function and processing function.

Add runtime value interface to m3cluster

---

client/client.go
client/etcd/client.go
client/etcd/client_test.go
kv/etcd/options.go
kv/etcd/store.go
kv/etcd/store_test.go
services/client/services_test.go

This PR allows users to specify namespace when creating KV store as top level namespace to improve isolation between services.
This PR did not use the namespace feature in etcd because we need to upgrade to go 1.8 in order to use that, when we are ready to upgrade Go we can easily change the impl to use etcd namespace
@xichen2020 @jeromefroe  @dgromov

Allow user to specify namespace in KV

---

services/placement/algo/sharded.go
services/placement/algo/sharded_helper.go
services/placement/algo/sharded_helper_test.go
services/placement/algo/sharded_test.go
services/placement/placement.go
services/placement/placement_test.go
services/placement/service/placementservice.go

This diff optimizes shard distribution in the placement algorithm, this issue was found during the investigation of a case that the weights of the candidate instances differs slightly (see TestMinorWeightDifference), but the original algorithm caused the node with lower weight to be underloaded, the difference in loads among the cluster is disproportional to the difference in weights when the weight difference is small.
This diff introduces a Optimize() function in PlacementHelper and tries to bring up the load closer to the target load. This function also leads to a few potential improvements in the algo which will be tried in future diffs.
@xichen2020 @dgromov

Optimize shard distribution

---

services/placement/algo/non_sharded.go
services/placement/algo/sharded.go
services/placement/algo/sharded_helper.go
services/placement/algo/sharded_helper_test.go
services/placement/algo/sharded_test.go
services/placement/placement.go
services/placement/placement_test.go
services/placement/service/placementservice.go
services/placement/service/placementservice_test.go

The placement clone is now create once before going through all the
shards. This commit also moves a bunch of stuff into placement.go from
the algo module.

placement no longer gets cloned for every shard in MarkShardAvaialble

---

kv/util/runtime/value_test.go
services/placement/config.go
services/placement/config_test.go

cc @jeromefroe 
This PR removes namespace from watcher configuration and instead explicitly pass in the kv store so we can create the store outside the config and reuse the store if needed.

Remove namespace from watcher configuration

---

client/client.go
client/etcd/client.go
client/etcd/client_test.go
services/client/options.go
services/client/services.go
services/client/services_test.go
services/client/storage.go
services/client/storage_test.go
services/client/util.go
services/client/util_test.go
services/config.go
services/config_test.go
services/services.go
services/services_test.go
services/types.go

Right now by default the placement data and metadata data in service discovery service are stored under _sd.placement and _sd.metadata namespace. This pr adds a new method to allow users to provide custom namespace to override those namespaces. So that we could support the r2 placement being accessible from both ServiceDiscovery interface and kv.Store interface although the value is stored in a custom namespace on etcd.
For example if a namespace of "/test_placement" was provided, the placement data for service: "statsdex_m3dbnode" could be accessible under "/test_placement/[env]/statsdex_m3dbnode".
In the future we could allow overriding the default namespace for leader service and heartbeat service as well.
@xichen2020 @prateek @jeromefroe @schallert @dgromov

Support custom namespace override in service discovery

---

placement/placement_mock.go
placement/service/service.go
placement/service/service_test.go
placement/storage/storage.go
placement/storage/storage_test.go
placement/types.go
services/client/etcd/services.go
services/client/etcd/services_test.go
services/services_mock.go
services/types.go

placement.Service used to expose Delete(), SetPlacement and Placement(), which are also exposed from placement.Storage interface, now that we also need to expose SetProto() and Proto(), this pr made placement.Storage embedded in placement.Service interface so that future updates in the placement.Storage interface are available through placement.Service as well.
this pr also moved Dryrun logic to placement.Storage.

Embed placement.Storage in placement.Service

---

kv/util/types.go
kv/util/util.go
kv/util/util_test.go

This PR adds utility functions to `kv` to watch for updates and validate that the updates fall within the pre-specified bounds. These functions will promote defensive programming and help callers guard against incorrect values being set in KV. I took a narrow approach here, only validating bounds for numeric types, but it might make sense to expand these changes to a more generic `validate` function that can check any type.
Update: Decided to take Prateek's advice and make the validation function more agnostic to the validation that should be performed.
cc @cw9 @xichen2020 @prateek

[util] Add utility functions for validating updates to watch variables

---

placement/algo/mirrored.go
placement/algo/mirrored_test.go
placement/algo/sharded.go
placement/algo/sharded_helper.go
placement/algo/sharded_test.go
placement/selector/common.go
placement/selector/mirrored.go
placement/selector/mirrored_test.go
shard/shard.go
shard/shard_test.go
shard/types.go

1, Allow replacing instance with Leaving instance in current placement.
2, When removing multiple instances, make sure their shards were only moved to non-leaving instances in the placement.
3. Add Equals() to the Shard interface.

Mirror placement algo changes

---

.travis.yml
kv/etcd/store.go
placement/algo/sharded_helper.go

This PR adds Go 1.8 and 1.9 to the versions of Go we test against in Travis. 
In addition, it seems the `unparam` linter has been updated and caught some new cases, so this PR also addresses the two instances of an error not being used that it found.

[travis] Add go 1.8 and 1.9 to travis tests

---

kv/util/util.go

This is a small PR to fix a minor nit I found where we used the formatting log functions where we don't need to.

[util] Use non-formatting log functions where appropriate

---

placement/placement_mock.go

Was doing the m3x package name upgrades. `m3em` need this; `m3db` needs m3em, etc...
/cc @cw9 @jeromefroe

Update mocks to new interface

---

glide.lock
glide.yaml
kv/util/util.go
kv/util/util_test.go

This PR returns the ValueWatches from the `WatchAndUpdate` functions so the caller can close them if they need to. Callers would then be able to ensure that the goroutines which watch for these updates will be closed.
cc @prateek @cw9

[util] Return watch from WatchAndUpdate functions

---

placement/algo/mirrored.go
placement/algo/mirrored_test.go
placement/algo/sharded.go
placement/algo/sharded_helper.go

In very rare case, the leaving shards could not be taken back due to rack conflicts.
For example, in a RF=2 case, instance a and b on rack1, instance c on rack2, instance d on rack3,
a and c owns shard 1, 
Remove a and c:
1, a give shard 1 to d
2, c give shard 1 to b
Add a and c back:
Now if a tries to get shard 1 back from d there will be a rack conflict because b(on the same rack with a) owns shard 1 as well.
This rack conflict can be resolved by having c take the shard back from b first, then a can take the shard back from d without rack conflict.
This diff introduces a loop that retries the shard reclaiming process as long as some instance are still making progress.

Fix the bug where instance could reclaim all of its leaving shards

---

kv/util/util_test.go

The unit test before only passes if the valueFn() was evaluated before the watch got the update, otherwise it'll block forever
@jeromefroe @xichen2020 @prateek

Fix flaky unit test

---

client/etcd/client.go
client/etcd/client_test.go
client/etcd/config.go
client/etcd/config_test.go
client/etcd/options.go
client/etcd/options_test.go

with this change we can distribute certs with langley and use them for auth, rather than exposing a bare etcd cluster to the company. can use a read-only cert in the proxy to avoid anyone accidentally trying to write stuff to KV after looking at the collector.

basic plumbing to allow setting client tls for kv clusters

---

client/etcd/client.go

Currently we use an empty tls config by default, which causes the auth to fail when no certificate provided in config, should use nil for the no-auth case

Use nil tls config by default

---

client/etcd/client.go
client/etcd/client_test.go
client/etcd/config.go
client/etcd/config_test.go
client/etcd/options.go
client/etcd/options_test.go
client/etcd/types.go

Refactor the logic around auth to keep the tls related logic isolated from etcd cluster logic

Refactor TLS configuration

---

integration/etcd/etcd.go
integration/etcd/types.go

This is required because I need to spin up a KV server and spin up M3DB using YAML to point to the KV server, i.e. can't use the call to `ConfigServiceClient()` on the created embedded KV store.

Expose endpoints for inntegration embedded KV server

---

client/etcd/client.go
client/etcd/client_test.go
glide.lock
glide.yaml

Seems current logic means the kv client in m3db will be using nulllogger as well, we probably need to upgrade all repos with this change, seems the only place with a real logger with the previous version is the one in m3aggregator where we explicitly set a logger with Warn level.
@robskillington @xichen2020 @prateek @jeromefroe

Use logger in config service client as default logger for kv client

---

services/leader/election/client_test.go

We want to ensure that even if a session dies we can still look up the
leader. This exercises that behavior in the unit tests.

[leader] Expand unit test for dead leader session

---

placement/algo/mirrored.go
placement/algo/non_sharded.go
placement/algo/sharded.go
placement/algo/sharded_helper.go
placement/algo/sharded_helper_test.go
placement/algo/sharded_test.go
placement/service/service.go
placement/types.go

cc @cw9
This PR exposes the `MarkAllShardsAvailable` API to mark all shards available where applicable.

Add MarkAllShardsAvailable to mark initializing shards available where applicable

---

placement/selector/mirrored.go
placement/selector/mirrored_test.go
placement/service/service_test.go

Also included a change to start the ShardSetID from 1 instead of 0.
@xichen2020

Reuse the same shard set id when adding back leaving instances

---

.travis.yml
client/etcd/client.go
client/etcd/client_test.go
client/etcd/config.go
client/etcd/config_test.go
client/etcd/options.go
client/etcd/options_test.go
client/etcd/types.go
glide.lock
glide.yaml
integration/etcd/etcd_test.go
services/leader/election/client.go

cc @cw9 @schallert 
This PR upgrades etcd client to 3.2.10 and grpc to 1.7.3, along with related dependency upgrades. It appears that the upgrade has fixed an issue seen with etcd before where a small percentage of clients do not receive key-value updates.
This upgrade however does require go version >= 1.8.

Upgrade etcd client to 3.2.10 to pick up latest client-side load balancer fixes

---

placement/selector/mirrored.go
placement/selector/non_mirrored.go
placement/service/service_test.go

Allow replace with less weight when partial replace is allowed by the options. The algorithm already supports that, in which case the algorithm will fill up the new host and distribute the rest of the load to the rest of the cluster evenly. But right now instance selector is returning errors regardless of the options.
This only affects the non-mirrored mode, while mirrored mode does not allow partial replace and requires the weight to be equal between the new and old instances.
@xichen2020

Allow replace with less weight in instance selector

---

placement/selector/non_mirrored.go
placement/selector/non_mirrored_test.go
placement/service/service_test.go

The algorithm will do the rebalance
@xichen2020

Allow candidate instance with rack conflicts when partial replace is enabled

---

services/heartbeat/etcd/store.go
services/heartbeat/etcd/store_test.go

kv watch by default will do a get() upon creation, which will call heartbeatStore.Get(), for a service with no heartbeats it will return an empty string, so all watch should expect a notification soon after creation regardless whether there is any heartbeat for the service.
@schallert

Fix flaky test in heartbeat store

---

placement/algo/mirrored.go
placement/algo/mirrored_test.go
placement/algo/sharded.go
placement/algo/sharded_helper.go
placement/algo/sharded_test.go
placement/options.go
placement/options_test.go
placement/types.go

1, Added ShardStateType in placement/types.go: 
- By default we will use TransitionShardState, which includes Initializing, Available, Leaving states, for M3DB and M3Agg
- SimpleShardState will only have shards in Available state, can be used by the cache or indexer
2, Algo will pick up the new option in tryCleanupShardState()

Add an option to control the shard states in the placement

---

kv/mem/store.go
kv/mem/store_test.go

Previously when you delete a key from mem store and set a new value for the key, the new value will be of version 1 which might not look like newer than the value before the deletion, this pr adds a revision field similar to what kv store has.
@xichen2020

Update mem value to behave the same as kv value

---

placement/options.go
placement/options_test.go
placement/placement_mock.go
placement/selector/non_mirrored.go
placement/selector/non_mirrored_test.go
placement/service/service_test.go
placement/types.go

This diff adds an option to allow the non-mirrored selector to add all candidates at once. This will be beneficial in caching tiers where each host may run more than one instance of the caching process.

[selector] Add option to add all candidates in non-mirrored selector

---

placement/selector/non_mirrored.go
placement/selector/non_mirrored_test.go
placement/service/service_test.go

Propagate the option to add all candidates in calls to replace all instances.

[service] Update replace selector to support adding all instances

---

placement/algo/mirrored_test.go
placement/algo/sharded.go
placement/algo/sharded_helper.go
placement/algo/sharded_test.go

Previously we always marks all shards as available for the initial placement, this pr allows the behavior to be configurable. 
- If the placement use `IncludeTransitionalShardStates`, which is the case in m3agg and m3db, then the placement will leave the shards in initial states.
- If the placement use `StableShardStateOnly`, which is the mode for cache and ingesters, then the shards will be marked as available after placement change.
@xichen2020 @robskillington @richardartoul

Do not mark shards as available by default in initial placement

---

etcd/watchmanager/manager.go
etcd/watchmanager/manager_test.go
kv/etcd/options.go
kv/etcd/store.go
kv/etcd/store_test.go

Some use cases require specifying the start revision of a watch request.
Since our only use case so far needs the start revision at a store level
as opposed to on a per-watch basis, this PR implements watch revision
support at the store level.
Includes tests to make sure that we can safely specify a start revision
that has been compacted or one that is in the future with no issues.

[kv] Support watch start revision in watch store

---

client/etcd/client.go
client/etcd/options.go
client/etcd/types.go

When M3 processes using m3cluster for service discovery comes up, a lot of processes will log a fatal error message and fail if they cannot start up.  
This is fine but can cause a large amount of DNS requests to be issued if restarted by a processes supervisor very frequently.  To avoid some of these thundering herd issues if a KV client is down, we add some level of backoff when trying to connect to service discovery.

Add retry options for creating etcd client
